package com.shopping.userservice.domain;

/**
 * @author devagoud
 */
public enum RoleNames {
    SUPER_ADMIN,PUBLISHER,CONTENT_ADMIN,CONTENT_DEVELOPER,STUDENT,CONTENT_UPLOADER,INSTRUCTOR,USER_MANAGER,FINANCE,SHIPPING_MANAGER,SHIPPING_COORDINATOR
}
